export {
  uploadIcon,
  uploadUserAvatar,
  uploadSpaceIcon,
  uploadWorkspaceIcon,
  removeAvatar,
  removeSpaceIcon,
  removeWorkspaceIcon,
  getWorkspaceImages,
  uploadLibraryImage,
  deleteWorkspaceImage,
  renameWorkspaceImage,
  getGallerySettings,
  updateGallerySettings,
} from "./attachment-service.ts";
